#!/bin/zsh
# ================================================
# ================================================
# ================================================

# ------------------------------------------------
# CONFIGURATION ----------------------------------
# ------------------------------------------------

# IP/domain name || local port
# ------------------------------------------------

#_upload_port="esp_0b9fa1.local"
_upload_port="192.168.1.60"

_local_tty_dev="/dev/tty.SLAB_USBtoUART"

_base_environment="nodemcuv2"

# ------------------------------------------------
# MAIN -------------------------------------------
# ------------------------------------------------

# Determine upload port
# ------------------------------------------------
if [[ -z $1 ]] ; then
  if [[ -e $_local_tty_dev ]] ; then
    echo "Uploading locally to: `stylize $_local_tty_dev`"
    _upload_port=$_local_tty_dev
    _environment=$_base_environment
  else
    echo "Uploading via OTA to: `stylize $_upload_port`"
    _environment=$_base_environment"_ota"
  fi
else
  _environment=$1
fi

# Prompt
# ------------------------------------------------
echo "Environment: `stylize $_environment`"
print-row -
echo -n "Run? [ENTER] "
read

# Run
# ------------------------------------------------
if platformio run --target upload --environment $_environment --upload-port=$_upload_port; then
  _message="Success."
else
  _message="Failed to upload."
fi
