#!/bin/zsh
# ================================================
# ZSH->UPLOAD ====================================
# ================================================
source .env

# ------------------------------------------------
# GLOBALS ----------------------------------------
# ------------------------------------------------
_base_environment="nodemcuv2"

# ------------------------------------------------
# MAIN -------------------------------------------
# ------------------------------------------------

# Determine upload port
# ------------------------------------------------
if [[ -z $1 ]] ; then
  if [[ -e $LOCAL_TTY_DEV ]] ; then
    echo "Uploading locally to: `stylize $LOCAL_TTY_DEV`"
    ESP_UPLOAD_PORT=$LOCAL_TTY_DEV
    _environment=$_base_environment
  else
    echo "Uploading via OTA to: `stylize $ESP_UPLOAD_PORT`"
    _environment=$_base_environment"_ota"
  fi
else
  _environment=$1
fi

# Prompt
# ------------------------------------------------
echo "Environment: `stylize $_environment`"
print-row -
echo -n "Run? [ENTER] "
read

# Run
# ------------------------------------------------
if platformio run --target upload --environment $_environment --upload-port=$ESP_UPLOAD_PORT; then
  _message="Success."
else
  _message="Failed to upload."
fi
