#!/bin/zsh


if [[ -e /dev/tty.SLAB_USBtoUART ]] ; then
  echo "Device found locally."
  _environment="nodemcuv2"
else
  echo "Device not found locally; uploading via OTA."
  _environment="nodemcuv2_ota"
fi

platformio run --target upload --environment $_environment
